### ISSUE TITLE
Favorite Page

### ISSUE THREAD

**Issue by ArianeDahl** [ArianeDahl/capstone-project#10]
## Value Proposition

**As a** User
**I want to** see my favorites on a separate page 
**so that** so that I can find them easily in the future
​

## Description

I want the ability to view a list of all my favorite fruits on a separate page, accessible via a link or button on the Fruits page.
​

## Acceptance Criteria

- [ ] Clicking on the favorite icon on the navbar will take the user to a seperate page
- [ ] On the page the favorites fruits and veggies will be displayed 
- [ ] The items are displayed in alphabetical order
- [ ] users can easily access the favorite page from any screen within the app
      ​

## Tasks

- [ ]Create a new branch and a new page "favorites.js"
- [ ] Add a link o the Fruits and Veggies page and a link to the new page
- [ ] Store & retrieve favorite fruits/ veggies data (local storage)
- [ ] Display favorite items from local storage on the new page
      ​
