### ISSUE TITLE
Add Images

### ISSUE THREAD

**Issue by ArianeDahl** [ArianeDahl/capstone-project#12]
## Value Proposition

**As a** User
**I want to** I want to be able to see images of the available fruits and veggies
**so that** I can get a better understanding of what they look like.
​

## Description
On the availability list an image is displayed next to the name.
When I click on the fruit name or image, I would like to be taken to a details page.
​

## Acceptance Criteria

- [ ] The image is displayed next to the name
- [ ] in the list of available fruits and veggies and the details page
      ​

## Tasks

- [ ] Create a new branch 
- [ ] add images to assets folder
- [ ] add path to each item in the data.js
- [ ] add data to availability page and detail page

      ​
