### ISSUE TITLE
Add Back Button

### ISSUE THREAD

**Issue by ArianeDahl** [ArianeDahl/capstone-project#13]
## Value Proposition

**As a** User
**I want to** I want a button on every page (except the home page)
**so that** I can get to the previous page easily
​

## Description

A button that takes the user to the previous page.
​

## Acceptance Criteria

- [ ] A button is displayed on the availability lists and the detail page
- [ ] Clicking the button will take the user to the previous page
      ​

## Tasks

- [ ] Create a new branch and a component "BackButton"
- [ ] Create a button and add export it to the pages needed
- [ ] Import button and add the useRouter hook
- [ ] Add some styling (don't spend too much time with it)
      ​
