### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by ArianeDahl** [ArianeDahl/capstone-project#17]
## Value Proposition

**As a** user
**I want to** be able to leave comments on suggested recipes
**so that** I can share my thoughts with others and find useful feedback. 
​

## Description

When I open the app and navigate to the details page with the suggested recipes section, I would like to see a form where I can leave comments. The interface of the form should be clear and easy to use. 
​

## Acceptance Criteria

- [ ] Type and submit comments on recipes
- [ ] Form: Date, section for comments, rating symbols
- [ ] Bonus: Being able to filterbcomments by date, rating
      ​

## Tasks

- [ ] create a branch and a new component
- [ ] Create a form for leaving comments
- [ ] Implement a storage system to store user comments for each recipe
- [ ] Create a way for users to filter comments left by others (Bonus)
      ​
