### ISSUE TITLE
DeleteButton

### ISSUE THREAD

**Issue by ArianeDahl** [ArianeDahl/capstone-project#19]
## Value Proposition

**As a** user
**I want to** be able to delete comments that I have posted on the recipes page
**so that** I can manage my own comments and keep the page tiny. 
​

## Description

I should see a delete button next to each of my comments.  When the user clicks on the delete button, the comment gets removed and a confirmation message indicates that the comment has been successfully deleted. 
​

## Acceptance Criteria

- [ ] A delete button next to the comments
- [ ] When clicking the button the selected comment disappears 
- [ ] confirmation message appears
      ​

## Tasks

- [ ] Create branch and component "DeleteButton"
- [ ] Create and implement the delete button
- [ ] handle the deletion of comments and removing them from the page.
- [ ] Implement a confirmation message that appears 
      ​
