### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by ArianeDahl** [ArianeDahl/capstone-project#2]
## Value Proposition

**As a** user
**I want to** choose between fruits and vegetables in the first place
**so that**  it's easier to find a specific fruit/ vegetable and it's be easier to get inspiration
​

## Description

![Homepage](https://user-images.githubusercontent.com/122229978/222716932-eb26f911-f691-4461-b246-22befaebfc69.png)

## Acceptance Criteria

- [ ] On the homepage you can see what month it is
- [ ] A short text tells you that the app is about seasonal fruits/ veggies
- [ ] You can choose between fruits or vegetables (later on the buttons will lead the user to a list)

​

## Tasks

- [ ] create a branch
- [ ] create a heading and paragraph with a welcoming and descriptive text
- [ ] create two buttons- fruits & vegetables- that are clickable       ​

**Comment by SarahWett** [comment]
Love this short but pretty descriptive intro text of yours! 
Looks good :)

**Comment by MartinK1983** [comment]
nice
