### ISSUE TITLE
Navigation 2.0

### ISSUE THREAD

**Issue by ArianeDahl** [ArianeDahl/capstone-project#21]
## Value Proposition

**As a** user 
**I want to**  be able to navigate through the app 
**so that** I can  easily  access the different sections.
​

## Description

I want to see a clear and visually appealing navigation bar that allows me to quickly access the home page, fruits section, and vegetables section (availability list). I also want to be able to go back to the previous page easily.

## Acceptance Criteria

- [ ] A clear and visually appealing navigation bar
- [ ] Icon (fruit) that leads to availability list for fruits
- [ ] Icon (veggie) that leads to availability list for veggies
- [ ] Icon (arrow) that leads to the previous page
      ​

## Tasks

- [ ] Create a branch and Navigation component
- [ ] Choose icons, create the component, implement icons in a link 
- [ ] Add some styling
- [ ] Implement the component in _app.js 
      ​
