### ISSUE TITLE
Availability-List

### ISSUE THREAD

**Issue by ArianeDahl** [ArianeDahl/capstone-project#3]
## Value Proposition

**As a** ... user
**I want to** see a list of seasonal fruits or vegetables
**so that** I can get an overview of available fruits/ vegetables
​

## Description

![List](https://user-images.githubusercontent.com/122229978/222735981-88ebda69-1456-48ad-9c67-953398448f45.png)

​

## Acceptance Criteria

- [ ] The list displays the available fruits/ vegetables of the month
- [ ] Each listed item shows the name and a picture of the given fruit/ vegetable
- [ ] Clicking on one item will lead the user to a detail page

      ​

## Tasks

- [ ] create a branch
- [ ] create a component Availability and an u-list
- [ ] fetch the data via its availability criteria and render a list
