### ISSUE TITLE
Detail Page

### ISSUE THREAD

**Issue by ArianeDahl** [ArianeDahl/capstone-project#4]
## Value Proposition

**As a** user
**I want to** I want to see the availability of my selected fruit/ vegetable and get some recipe suggestions
**so that** I can get some inspiration and reach my goal to eat more seasonal fruits/ veggies
​

## Description

![Detail_page](https://user-images.githubusercontent.com/122229978/222748529-a72ba457-d23f-465f-bfa7-9c37eae9f749.png)

​

## Acceptance Criteria

- [ ] Clicking an item of the list will lead the user to a detail page
- [ ] The name, an image and the availability
- [ ] A few recipes are displayed
- [ ] Bonus: Information about certain vitamins and what they're good for
      ​

## Tasks

- [ ] create a branch
- [ ] create the component DetailsPage
- [ ] Add the heading, paragraph, image and fetch the data (data.js)
- [ ] fetch data (recipes-api) and select about five recipes that will be displayed on the details page

**Comment by pung-one** [comment]
inspiring!

**Comment by ArianeDahl** [comment]
Images will follow with another US!
