### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by ArianeDahl** [ArianeDahl/capstone-project#7]
## Value Proposition

**As a** User
**I want to** want to understand right away how to get from one page to another
**so that**  I can navigate easily from one pag to the other
​

## Description

![NavBar](https://user-images.githubusercontent.com/122229978/224569287-41eb198d-14ef-4e7c-9781-24ab17d58e6e.png)

​

## Acceptance Criteria

- [ ] Sticky nav bar on the bottom of the page
- [ ] By clicking on an icon the user gets to the selected page (home, search, favourites)
- [ ] Available on every page
      ​

## Tasks

- [ ] Create new branch and a component
- [ ]Link to home page, favourites and search bar
- [ ] Add Icons
      ​
