### ISSUE TITLE
Add Recipes

### ISSUE THREAD

**Issue by ArianeDahl** [ArianeDahl/capstone-project#8]
## Value Proposition

**As a** User
**I want to** a few recipes to be suggested for the selected fruit/ vegetable
**so that** I can get some ideas what to cook/ bake with it
​

## Description
​
![Detail_page](https://user-images.githubusercontent.com/122229978/224570135-f1e28cd1-f1f4-4a81-9d8e-230fe333360f.png)

## Acceptance Criteria

- [ ] On the detail page of a fruit or vegetable a few recipes get displayed
- [ ] Only a few recipes (max 5), so the page is not "overloaded"

      ​

## Tasks

- [ ] create a new branch
- [ ] fetch the recipes for veggies & fruits with SWR
- [ ] pass the data to detail page as props
- [ ] Use a dynamic parameter for the recipe id (route)
      ​
