### ISSUE TITLE
Favorite Button

### ISSUE THREAD

**Issue by ArianeDahl** [ArianeDahl/capstone-project#9]
## Value Proposition

**As a** User
**I want to** be able to mark my favorite fruits & veggies
**so that** I can easily find them in the future
​

## Description
I want to see a heart-shaped button next to each fruit item on the Fruits & Veggie page, which will allow me to toggle its favorite status. When I click the button, it should change its appearance (e.g. turn red). If I click the button again, it should toggle back to its original appearance.

​

## Acceptance Criteria

- [ ] Button on each item of the Fruits & Veggie page  
- [ ] Button on the detail page
- [ ] When a user clicks on the favorite button, its status toggles between favorite and non-favorite.
      ​

## Tasks

- [ ] Creat a branch a component FavoriteButton
- [ ] Add toggle function
- [ ] Update the appearance of the favorite button to indicate its status (color of icon)
      ​
